<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnouncementService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Webkul\UVDesk\SupportCenterBundle\Controller\Announcement' shared autowired service.
     *
     * @return \Webkul\UVDesk\SupportCenterBundle\Controller\Announcement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Announcement'] = $instance = new \Webkul\UVDesk\SupportCenterBundle\Controller\Announcement(($container->services['translator'] ?? $container->load('getTranslatorService')), ($container->services['user.service'] ?? $container->load('getUser_ServiceService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Announcement', $container));

        return $instance;
    }
}
