<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountValidationService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Webkul\UVDesk\SupportCenterBundle\Form\AccountValidation' shared autowired service.
     *
     * @return \Webkul\UVDesk\SupportCenterBundle\Form\AccountValidation
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Webkul\\UVDesk\\SupportCenterBundle\\Form\\AccountValidation'] = new \Webkul\UVDesk\SupportCenterBundle\Form\AccountValidation();
    }
}
