<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentActivityRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Webkul\UVDesk\CoreFrameworkBundle\Repository\AgentActivityRepository' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Repository\AgentActivityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Repository\\AgentActivityRepository'] = new \Webkul\UVDesk\CoreFrameworkBundle\Repository\AgentActivityRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
