<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Webkul\UVDesk\SupportCenterBundle\Controller\Article' shared autowired service.
     *
     * @return \Webkul\UVDesk\SupportCenterBundle\Controller\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Article'] = $instance = new \Webkul\UVDesk\SupportCenterBundle\Controller\Article(($container->services['user.service'] ?? $container->load('getUser_ServiceService')), ($container->services['uvdesk.service'] ?? $container->load('getUvdesk_ServiceService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['translator'] ?? $container->load('getTranslatorService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Article', $container));

        return $instance;
    }
}
