<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBootstrappingProjectService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.Webkul\UVDesk\CoreFrameworkBundle\Guides\BootstrappingProject' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Guides\BootstrappingProject
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.Webkul\\UVDesk\\CoreFrameworkBundle\\Guides\\BootstrappingProject'] = new \Webkul\UVDesk\CoreFrameworkBundle\Guides\BootstrappingProject();
    }
}
