<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrandingService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Webkul\UVDesk\SupportCenterBundle\Controller\Branding' shared autowired service.
     *
     * @return \Webkul\UVDesk\SupportCenterBundle\Controller\Branding
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Branding'] = $instance = new \Webkul\UVDesk\SupportCenterBundle\Controller\Branding(($container->services['user.service'] ?? $container->load('getUser_ServiceService')), ($container->services['translator'] ?? $container->load('getTranslatorService')), ($container->services['uvdesk.core.file_system.service'] ?? $container->load('getUvdesk_Core_FileSystem_ServiceService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Branding', $container));

        return $instance;
    }
}
