<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateTicketService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Webkul\UVDesk\CoreFrameworkBundle\Form\CreateTicket' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Form\CreateTicket
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\CreateTicket'] = new \Webkul\UVDesk\CoreFrameworkBundle\Form\CreateTicket();
    }
}
