<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultUserService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.App\Console\Wizard\DefaultUser' shared autowired service.
     *
     * @return \App\Console\Wizard\DefaultUser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.App\\Console\\Wizard\\DefaultUser'] = new \App\Console\Wizard\DefaultUser($container, ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['.container.private.security.password_encoder'] ?? $container->load('get_Container_Private_Security_PasswordEncoderService')));
    }
}
