<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventListener\ExceptionSubscriber' shared autowired service.
     *
     * @return \App\EventListener\ExceptionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\EventListener\\ExceptionSubscriber'] = new \App\EventListener\ExceptionSubscriber(($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService')), $container);
    }
}
