<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnvironmentVariablesService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.App\Console\EnvironmentVariables' shared autowired service.
     *
     * @return \App\Console\EnvironmentVariables
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.App\\Console\\EnvironmentVariables'] = new \App\Console\EnvironmentVariables($container);
    }
}
