<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailboxChannelService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Webkul\UVDesk\MailboxBundle\Controller\MailboxChannel' shared autowired service.
     *
     * @return \Webkul\UVDesk\MailboxBundle\Controller\MailboxChannel
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Webkul\\UVDesk\\MailboxBundle\\Controller\\MailboxChannel'] = $instance = new \Webkul\UVDesk\MailboxBundle\Controller\MailboxChannel(($container->services['user.service'] ?? $container->load('getUser_ServiceService')), ($container->privates['Webkul\\UVDesk\\MailboxBundle\\Services\\MailboxService'] ?? $container->load('getMailboxServiceService')), ($container->services['translator'] ?? $container->load('getTranslatorService')), ($container->services['swiftmailer.service'] ?? ($container->services['swiftmailer.service'] = new \Webkul\UVDesk\CoreFrameworkBundle\SwiftMailer\SwiftMailer($container))));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('Webkul\\UVDesk\\MailboxBundle\\Controller\\MailboxChannel', $container));

        return $instance;
    }
}
