<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuickActionButtonCollectionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Webkul\UVDesk\CoreFrameworkBundle\Tickets\QuickActionButtonCollection' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Tickets\QuickActionButtonCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService'));

        if (isset($container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection'])) {
            return $container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection'];
        }
        $b = ($container->services['user.service'] ?? $container->load('getUser_ServiceService'));

        if (isset($container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection'])) {
            return $container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection'];
        }

        $container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection'] = $instance = new \Webkul\UVDesk\CoreFrameworkBundle\Tickets\QuickActionButtonCollection($a, ($container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Dashboard\\DashboardTemplate'] ?? $container->load('getDashboardTemplateService')), $b);

        $instance->add(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Ticket\QuickActionButtons\SavedReplies(), [0 => []]);
        $instance->add(new \Webkul\UVDesk\AutomationBundle\UIComponents\Ticket\QuickActionButtons\PreparedResponses(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))), [0 => []]);

        return $instance;
    }
}
