<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecaptchaRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Webkul\UVDesk\CoreFrameworkBundle\Repository\RecaptchaRepository' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Repository\RecaptchaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Repository\\RecaptchaRepository'] = new \Webkul\UVDesk\CoreFrameworkBundle\Repository\RecaptchaRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
