<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenderDashboardRoutineService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\RenderDashboardRoutine' shared autowired service.
     *
     * @return \Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\RenderDashboardRoutine
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Application\\Routine\\RenderDashboardRoutine'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\RenderDashboardRoutine(($container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Dashboard\\DashboardTemplate'] ?? $container->load('getDashboardTemplateService')));
    }
}
