<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSwiftmailer_Mailer_Mailer9381_TransportService extends App_KernelProdContainer
{
    /*
     * Gets the public 'swiftmailer.mailer.mailer_9381.transport' shared service.
     *
     * @return \Swift_Transport_EsmtpTransport
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Swift_Transport_Esmtp_AuthHandler([0 => new \Swift_Transport_Esmtp_Auth_CramMd5Authenticator(), 1 => new \Swift_Transport_Esmtp_Auth_LoginAuthenticator(), 2 => new \Swift_Transport_Esmtp_Auth_PlainAuthenticator(), 3 => new \Swift_Transport_Esmtp_Auth_NTLMAuthenticator()]);
        $a->setUsername('support@telenet.com.np');
        $a->setPassword('TGF4bWFuMDA3Kg==');
        $a->setAuthMode('login');

        $container->services['swiftmailer.mailer.mailer_9381.transport'] = $instance = new \Swift_Transport_EsmtpTransport(new \Swift_Transport_StreamBuffer(new \Swift_StreamFilters_StringReplacementFilterFactory()), [0 => $a], new \Swift_Events_SimpleEventDispatcher());

        $instance->setHost('mail.telenet.com.np');
        $instance->setPort(587);
        $instance->setEncryption('tls');
        $instance->setTimeout(30);
        $instance->setSourceIp(NULL);
        (new \Symfony\Bundle\SwiftmailerBundle\DependencyInjection\SmtpTransportConfigurator(NULL, ($container->privates['router.request_context'] ?? $container->getRouter_RequestContextService())))->configure($instance);

        return $instance;
    }
}
