<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicketVoterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Webkul\UVDesk\CoreFrameworkBundle\Security\TicketVoter' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Security\TicketVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Security\\TicketVoter'] = new \Webkul\UVDesk\CoreFrameworkBundle\Security\TicketVoter($container, ($container->privates['security.access.decision_manager'] ?? $container->getSecurity_Access_DecisionManagerService()));
    }
}
