<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUvdesk_Core_FileSystem_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'uvdesk.core.file_system.service' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\FileSystem\FileSystem
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['uvdesk.core.file_system.service'] = new \Webkul\UVDesk\CoreFrameworkBundle\FileSystem\FileSystem($container, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
