<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUvdesk_ExtensiblesService extends App_KernelProdContainer
{
    /*
     * Gets the public 'uvdesk.extensibles' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Framework\ExtendableComponentManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['uvdesk.extensibles'] = $instance = new \Webkul\UVDesk\CoreFrameworkBundle\Framework\ExtendableComponentManager($container);

        $a = ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
        $b = ($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService'));
        $c = ($container->services['user.service'] ?? $container->load('getUser_ServiceService'));

        $d = new \Webkul\UVDesk\CoreFrameworkBundle\Dashboard\AsideTemplate($a, $b, $c);
        $d->addPanelSidebar(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Sidebars\Account());
        $d->addPanelSidebar(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Sidebars\Apps());
        $d->addPanelSidebar(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Sidebars\Branding());
        $d->addPanelSidebar(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Sidebars\Productivity());
        $d->addPanelSidebar(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Sidebars\Reports());
        $d->addPanelSidebar(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Sidebars\Settings());
        $d->addPanelSidebar(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Sidebars\Users());
        $d->addPanelSidebar(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Panel\Sidebars\Knowledgebase());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Account\Profile());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Productivity\SavedReplies());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Productivity\Tags());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Productivity\TicketTypes());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Reports\AgentActivity());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Reports\Kudos());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Settings\Branding());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Settings\EmailSettings());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Settings\EmailTemplates());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Settings\SwiftMailer());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Themes\Helpdesk());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Users\Agents());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Users\Customers());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Users\Groups());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Users\Privileges());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Panel\Items\Users\Teams());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\AutomationBundle\UIComponents\Dashboard\Panel\Items\Productivity\PreparedResponses());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\AutomationBundle\UIComponents\Dashboard\Panel\Items\Productivity\Workflows());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\MailboxBundle\UIComponents\Dashboard\Panel\Items\Settings\Mailboxes());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Panel\Items\Knowledgebase\Announcement());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Panel\Items\Knowledgebase\Articles());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Panel\Items\Knowledgebase\Categories());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Panel\Items\Knowledgebase\Folders());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Panel\Items\Settings\BlockSpam());
        $d->addPanelSidebarItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Panel\Items\Themes\SupportCenter());
        $e = ($container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Dashboard\\DashboardTemplate'] ?? $container->load('getDashboardTemplateService'));
        $f = ($container->services['router'] ?? $container->getRouterService());
        $g = ($container->services['translator'] ?? $container->load('getTranslatorService'));

        $h = new \Webkul\UVDesk\CoreFrameworkBundle\Dashboard\NavigationTemplate($container, $a, $f, $c, $g);
        $i = new \Webkul\UVDesk\CoreFrameworkBundle\Dashboard\HomepageTemplate($f, $c, $g);

        $j = new \Webkul\UVDesk\CoreFrameworkBundle\Dashboard\Dashboard($e, $h, $i);
        $j->appendNavigation(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Navigation\Home());
        $j->appendNavigation(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Navigation\Reports());
        $j->appendNavigation(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Navigation\Ticket());
        $j->appendNavigation(new \Webkul\UVDesk\ExtensionFrameworkBundle\UIComponents\Dashboard\Navigation\Apps());
        $j->appendNavigation(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Navigation\Knowledgebase());
        $j->appendHomepageSection(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Sections\Productivity());
        $j->appendHomepageSection(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Sections\Reports());
        $j->appendHomepageSection(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Sections\Settings());
        $j->appendHomepageSection(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Sections\Users());
        $j->appendHomepageSection(new \Webkul\UVDesk\ExtensionFrameworkBundle\UIComponents\Dashboard\Homepage\Sections\Apps());
        $j->appendHomepageSection(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Homepage\Sections\Knowledgebase());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\AgentActivity());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\Agents());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\Branding());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\Customers());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\EmailSettings());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\EmailTemplates());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\Groups());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\Kudos());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\Privileges());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\SavedReplies());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\SwiftMailer());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\Tags());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\Teams());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Homepage\Items\TicketTypes());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\AutomationBundle\UIComponents\Dashboard\Homepage\Items\PreparedResponses());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\AutomationBundle\UIComponents\Dashboard\Homepage\Items\Workflows());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\ExtensionFrameworkBundle\UIComponents\Dashboard\Homepage\Items\ExploreApps());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\MailboxBundle\UIComponents\Dashboard\Homepage\Items\Mailbox());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Homepage\Items\Announcement());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Homepage\Items\Articles());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Homepage\Items\Categories());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Homepage\Items\Folders());
        $j->appendHomepageSectionItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Homepage\Items\SpamSettings());
        $k = new \Webkul\UVDesk\CoreFrameworkBundle\Dashboard\SearchTemplate($b, $g, $c);
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\AgentActivity());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\Agents());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\Apps());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\Branding());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\EmailSettings());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\EmailTemplates());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\Groups());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\Kudos());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\Privileges());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\SavedReplies());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\Tags());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\Teams());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\TicketTypes());
        $k->appendSearchItem(new \Webkul\UVDesk\CoreFrameworkBundle\UIComponents\Dashboard\Search\Tickets());
        $k->appendSearchItem(new \Webkul\UVDesk\AutomationBundle\UIComponents\Dashboard\Search\PreparedResponses());
        $k->appendSearchItem(new \Webkul\UVDesk\AutomationBundle\UIComponents\Dashboard\Search\Workflows());
        $k->appendSearchItem(new \Webkul\UVDesk\ExtensionFrameworkBundle\UIComponents\Dashboard\Search\Apps());
        $k->appendSearchItem(new \Webkul\UVDesk\MailboxBundle\UIComponents\Dashboard\Search\Mailbox());
        $k->appendSearchItem(new \Webkul\UVDesk\MailboxBundle\UIComponents\Dashboard\Search\SwiftMailer());
        $k->appendSearchItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Search\Announcement());
        $k->appendSearchItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Search\Articles());
        $k->appendSearchItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Search\Categories());
        $k->appendSearchItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Search\Customers());
        $k->appendSearchItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Search\Folders());
        $k->appendSearchItem(new \Webkul\UVDesk\SupportCenterBundle\UIComponents\Dashboard\Search\SpamSettings());

        $instance->addComponent($d);
        $instance->addComponent($j);
        $instance->addComponent($e);
        $instance->addComponent($i);
        $instance->addComponent($h);
        $instance->addComponent($k);
        $instance->addComponent(($container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection'] ?? $container->load('getQuickActionButtonCollectionService')));
        $instance->addComponent(new \Webkul\UVDesk\CoreFrameworkBundle\Tickets\WidgetCollection());

        return $instance;
    }
}
