<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidation_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'validation.service' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Services\ValidationService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['validation.service'] = new \Webkul\UVDesk\CoreFrameworkBundle\Services\ValidationService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), $container, ($container->services['translator'] ?? $container->load('getTranslatorService')));
    }
}
