<?php

namespace ContainerDGeH6xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflowXHRService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Webkul\UVDesk\AutomationBundle\Controller\Automations\WorkflowXHR' shared autowired service.
     *
     * @return \Webkul\UVDesk\AutomationBundle\Controller\Automations\WorkflowXHR
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Webkul\\UVDesk\\AutomationBundle\\Controller\\Automations\\WorkflowXHR'] = $instance = new \Webkul\UVDesk\AutomationBundle\Controller\Automations\WorkflowXHR(($container->services['user.service'] ?? $container->load('getUser_ServiceService')), ($container->services['uvdesk.automations.workflows'] ?? $container->load('getUvdesk_Automations_WorkflowsService')), ($container->services['ticket.service'] ?? $container->load('getTicket_ServiceService')), ($container->services['translator'] ?? $container->load('getTranslatorService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('Webkul\\UVDesk\\AutomationBundle\\Controller\\Automations\\WorkflowXHR', $container));

        return $instance;
    }
}
