<?php

namespace Container18Ja2sV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardTemplateService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\CoreFrameworkBundle\Dashboard\DashboardTemplate' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Dashboard\DashboardTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Framework/ExtendableComponentInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Dashboard/DashboardTemplate.php';

        return $container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Dashboard\\DashboardTemplate'] = new \Webkul\UVDesk\CoreFrameworkBundle\Dashboard\DashboardTemplate($container, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['router'] ?? $container->getRouterService()));
    }
}
