<?php

namespace Container18Ja2sV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUvdesk_Automations_WorkflowsService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the public 'uvdesk.automations.workflows' shared autowired service.
     *
     * @return \Webkul\UVDesk\AutomationBundle\EventListener\WorkflowListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/EventListener/WorkflowListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Workflow/Event.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Agent/Create.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Agent/Delete.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/UserForgotPassword.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Agent/ForgotPassword.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Agent/Update.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Customer/Create.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Customer/Delete.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Customer/ForgotPassword.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Customer/Update.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Agent.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/AgentReply.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Collaborator.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/CollaboratorReply.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Create.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/CustomerReply.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Delete.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Group.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Note.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Priority.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Status.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Team.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/ThreadUpdate.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Type.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Workflow/Action.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Agent/MailAgent.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Agent/TransferTickets.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Customer/MailCustomer.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/MailUser.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/AddNote.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailAgent.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailCustomer.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailGroup.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailLastCollaborator.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailTeam.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MarkSpam.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateAgent.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateGroup.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateLabel.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdatePriority.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateStatus.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateTag.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateTeam.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateType.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        $container->services['uvdesk.automations.workflows'] = $instance = new \Webkul\UVDesk\AutomationBundle\EventListener\WorkflowListener($container, $a);

        $b = ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\Create($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\Delete($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\ForgotPassword($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\Update($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\Create($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\Delete($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\ForgotPassword($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\Update($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Agent($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\AgentReply($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Collaborator($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\CollaboratorReply($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Create($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\CustomerReply($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Delete($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Group($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Note($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Priority($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Status($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Team($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\ThreadUpdate($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Type($container, $b, $a));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\UserForgotPassword($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Agent\MailAgent($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Agent\TransferTickets($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Customer\MailCustomer($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\MailUser($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\AddNote($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailAgent($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailCustomer($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailGroup($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailLastCollaborator($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailTeam($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MarkSpam($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateAgent($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateGroup($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateLabel($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdatePriority($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateStatus($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateTag($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateTeam($container, $b, $a));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateType($container, $b, $a));

        return $instance;
    }
}
