<?php

namespace Container18Ja2sV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUser_ServiceService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the public 'user.service' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Services\UserService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Services/UserService.php';

        $a = ($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService'));

        if (isset($container->services['user.service'])) {
            return $container->services['user.service'];
        }

        return $container->services['user.service'] = new \Webkul\UVDesk\CoreFrameworkBundle\Services\UserService($container, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), $a);
    }
}
