<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container18Ja2sV\App_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container18Ja2sV/App_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/Container18Ja2sV.legacy');

    return;
}

if (!\class_exists(App_KernelProductionDebugContainer::class, false)) {
    \class_alias(\Container18Ja2sV\App_KernelProductionDebugContainer::class, App_KernelProductionDebugContainer::class, false);
}

return new \Container18Ja2sV\App_KernelProductionDebugContainer([
    'container.build_hash' => '18Ja2sV',
    'container.build_id' => '8d682ddf',
    'container.build_time' => 1661673217,
], __DIR__.\DIRECTORY_SEPARATOR.'Container18Ja2sV');
